apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra-web-app.fullname" . }}
  labels:
    {{- include "infra-web-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
    - port: 443
      name: https
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "infra-web-app.selectorLabels" . | nindent 4 }}
