image:
  repository: 821777302053.dkr.ecr.us-east-1.amazonaws.com/mpierre
  tag: "guerilla-web-app"

service:
  name: guerilla-web-app
  type: LoadBalancer
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8080}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:821777302053:certificate/f77165ee-d72c-4393-b574-5e7c1e80f339
  path: /
  hosts:
    - host: mpierre.ca
      paths:
        - path: /
          pathType: ImplementationSpecific

replicaCount: 1

resources: {}

autoscaling:
  enabled: false