pipeline {
    agent { 
        node {
            label 'docker-agent-python'
            }
    }
    triggers {
        // poll every 10 minutes
        pollSCM('H/10 * * * *')
    }
    stages {
        stage('Build') {
            steps {
                echo "Building.."
                sh '''
                python3 --version
                pip3 install -r ./python_app/requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
                sh '''
                pip install pytest
                pip show pytest
                export PATH="/home/jenkins/.local/bin:$PATH"
                pytest
                '''
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''
                python3 ./python_app/weather_app.py
                '''
            }
        }
    }
}